import { Button, VerticalBox, AboutSlint } from "std-widgets.slint";

struct WeatherRecord {
    temperature: float, // Temperature in degrees Celsius
    humidity: float,    // Humidity in percent
    timestamp: string,
}

export global ViewModel {
    in property <bool> have-data;
    in property <WeatherRecord> weather;
    in property <[WeatherRecord]> reccords;
}

export component TitleBar inherits Rectangle {
    in property <string> text <=> title-text.text;

    width: 100%;
    height: 30px;
    padding-top: 5px;
    padding-bottom: 5px;
    // background: #cccccc;
    title-text := Text {
        font-size: 16px;
    }
}

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    callback request-increase-value();

    width: 320px;
    height: 240px;

    VerticalBox {
        alignment: space-between;

        TitleBar {
            text: "Slint Weather Station";
        }
        Text {
            horizontal-alignment: center;
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
